spring:
  application:
    name: deplifybot
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: false
      okhttp:
        enabled: true
      client:
        config:
          telegram:
            url: ${TELEGRAM_API_URL}
            connect-timeout: 10000
            read-timeout: 15000
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 0s

telegram:
  bot:
    webhook:
      url: ${TELEGRAM_BOT_URL}
      secret: ${TELEGRAM_WEBHOOK_SECRET}

server:
  port: ${PORT}
