spring:
  application:
    name: deplifybot
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: false
      okhttp:
        enabled: true
      client:
        config:
          telegram:
            url: ${TELEGRAM_API_URL:https://example.com}/bot${TELEGRAM_BOT_TOKEN:dummy-token}
            connect-timeout: 10000
            read-timeout: 15000
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 0s

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs

telegram:
  bot:
    webhook:
      url: ${TELEGRAM_WEBHOOK_URL:https://example.com}
      path: /telegram/webhook

server:
  port: ${PORT:8080}
